const https=require('https');
const DECP='https://tabular-api.data.gouv.fr/api/resources/22847056-61df-452d-837d-8b8ceadbfc52/data/';
const TECH=['plomberie','chauffage','climatisation','électricité','maintenance','ventilation','cvc'];
const IDF=new Set(['75','77','78','91','92','93','94','95']);
function getJson(url,timeout=6500){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'TRIGORA/2.3','Accept':'application/json'}},res=>{let body='';res.on('data',d=>body+=d);res.on('end',()=>{if(res.statusCode>=200&&res.statusCode<300){try{resolve(JSON.parse(body))}catch{reject(new Error('Invalid JSON'))}}else reject(new Error('DECP HTTP '+res.statusCode))})});req.on('error',reject);req.setTimeout(timeout,()=>req.destroy(new Error('DECP timeout')))})}
function str(v){return v==null?'':String(v)}
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:null;const s=str(v).replace(/\s/g,'').replace(/€/g,'');let n=Number(s.replace(/,(?=\d{1,2}$)/,'.').replace(/\.(?=\d{3}(?:\D|$))/g,''));return Number.isFinite(n)?n:null}
function isIdf(r){const d=str(r.acheteur_departement_code||r.code_departement||r.acheteur_code_departement||'').padStart(2,'0').slice(0,2);if(IDF.has(d))return true;const z=str(r.acheteur_region_nom||r.acheteur_departement_nom||'').toLowerCase();return z.includes('île-de-france')||z.includes('ile-de-france')}
async function fetch(q){const p=new URLSearchParams({page_size:'60',donneesActuelles__exact:'true',objet__contains:q});const x=await getJson(DECP+'?'+p);return x.data||x.results||[]}
module.exports=async(req,res)=>{const settled=await Promise.allSettled(TECH.map(fetch));const rows=[],seen=new Set(),errors=[];for(const z of settled){if(z.status==='rejected'){errors.push(z.reason.message);continue}for(const r of z.value){const id=str(r.uid||r.id);if(id&&!seen.has(id)&&isIdf(r)){seen.add(id);rows.push(r)}}}const by=new Map();for(const r of rows){const siret=str(r.titulaire_id||r.titulaire_siret);const name=str(r.titulaire_nom);if(!siret&&!name)continue;const key=siret||name.toLowerCase();let c=by.get(key);if(!c){c={entity_id:siret||null,company:name||null,contracts:0,total_amount_eur:0,sectors:new Set(),buyers:new Set(),last_notification:null};by.set(key,c)}c.contracts++;const m=num(r.montant_rationalise??r.montant);if(m!=null)c.total_amount_eur+=m;const o=str(r.objet).toLowerCase();TECH.forEach(k=>{if(o.includes(k))c.sectors.add(k)});if(r.acheteur_nom)c.buyers.add(str(r.acheteur_nom));const d=str(r.dateNotification);if(d&&(!c.last_notification||d>c.last_notification))c.last_notification=d}const companies=[...by.values()].map(c=>({...c,sectors:[...c.sectors].slice(0,6),buyers:[...c.buyers].slice(0,5),total_amount_eur:Math.round(c.total_amount_eur*100)/100,signal_strength:Math.min(100,30+Math.min(c.contracts,5)*8+(c.total_amount_eur>=500000?25:0)+(c.sectors.size>=2?10:0))})).sort((a,b)=>b.signal_strength-a.signal_strength);res.statusCode=200;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');res.end(JSON.stringify({success:true,generated_at:new Date().toISOString(),scope:'Île-de-France / technique BTP',source_records:rows.length,upstream_errors:errors,company_count:companies.length,companies:companies.slice(0,50)}))};