const https=require('https');
const BOAMP='https://www.boamp.fr/api/explore/v2.1/catalog/datasets/boamp_piamp_concentrateur/records';
const DECP='https://tabular-api.data.gouv.fr/api/resources/22847056-61df-452d-837d-8b8ceadbfc52/data/';
const IDF=new Set(['75','77','78','91','92','93','94','95']);
const KEYWORDS={cvc:['cvc','chauffage','climatisation','ventilation','hvac','thermique'],plomberie:['plomberie','plombier','sanitaire','canalisation','eau potable'],electricite:['électricité','electricite','électrique','electrique','courant fort','courant faible','hta','basse tension','haute tension'],maintenance:['maintenance technique','maintenance multitechnique','exploitation technique','exploitation-maintenance','installations techniques','entretien technique']};
const TECH=/\b(bâtiment|batiment|construction|travaux|chantier|immeuble|logement|tertiaire|industriel|chaufferie|plomberie|chauffage|climatisation|ventilation|électricité|electricite|courant fort|courant faible|sanitaire|canalisation|réseau|reseau|maintenance technique|multitechnique|exploitation technique|ssi|sécurité incendie|securite incendie)\b/i;
function str(v){return v==null?'':String(v)}
function first(r,names){const ks=Object.keys(r||{});for(const n of names){const k=ks.find(x=>x.toLowerCase()===n.toLowerCase());if(k&&r[k]!=null&&r[k]!=='')return r[k]}for(const n of names){const k=ks.find(x=>x.toLowerCase().includes(n.toLowerCase()));if(k&&r[k]!=null&&r[k]!=='')return r[k]}return null}
function num(v){if(v==null)return null;if(typeof v==='number')return Number.isFinite(v)?v:null;const n=Number(str(v).replace(/\s/g,'').replace(/€/g,'').replace(/,/g,'.').replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:null}
function parse(v){if(typeof v!=='string')return v;try{return JSON.parse(v)}catch{return null}}
function flatten(v,o=[]){if(v==null)return o;if(Array.isArray(v)){v.forEach(x=>flatten(x,o));return o}if(typeof v==='object')Object.entries(v).forEach(([k,x])=>{o.push([k,str(x)]);flatten(x,o)});return o}
function nested(r,keys){const p=parse(r?.donnees);if(!p)return null;for(const [k,v] of flatten(p))if(keys.some(x=>k.toLowerCase().includes(x))){const n=num(v);if(n!=null)return n}return null}
function text(r){return [first(r,['objet','object','title','intitule','description','objet_du_marche']),first(r,['descripteur_libelle','famille_libelle','cpv','type_marche']),first(r,['nomacheteur','acheteur','acheteur_nom','acheteur_nom_officiel','organisme']),first(r,['ville','commune','acheteur_ville','lieu_execution'])].map(str).join(' ')}
function sector(t){const x=str(t).toLowerCase();for(const [s,ws] of Object.entries(KEYWORDS))if(ws.some(w=>x.includes(w)))return s;return null}
function region(r){const d=[first(r,['code_departement','code_departement_prestation','acheteur_code_departement']),first(r,['codepostal','code_postal','acheteur_code_postal','cp'])].filter(Boolean).flatMap(v=>Array.isArray(v)?v:[v]).map(str);if(d.some(x=>IDF.has(x.padStart(2,'0').slice(0,2))))return'Île-de-France';const t=text(r).toLowerCase();return /\bparis\b|\bversailles\b|\bmarne[- ]la[- ]vallée\b|\bboulogne[- ]billancourt\b|\bnanterre\b|\bcréteil\b|\bcreteil\b|\bévry\b|\bevry\b|\bcorbeil[- ]essonnes\b|\bmelun\b|\bmontreuil\b|\bsarcelles\b|\bcergy\b|\bsaint[- ]denis\b/.test(t)?'Île-de-France':null}
function eventType(r){const n=str(first(r,['nature','nature_libelle','type_avis','type','modification_type'])).toLowerCase();if(/attribution|résultat|resultat|decp/.test(n))return'attribution';if(n.includes('annulation'))return'annulation';if(n.includes('rectificatif'))return'rectificatif';if(/avis de marché|appel d’offres|appel d'offres|appel/.test(n))return'appel_offres';return n||'autre'}
function score(r){const t=text(r),sec=sector(t),reg=region(r),evt=eventType(r),amount=num(first(r,['montant','amount','montant_ht','value','valeur']))??nested(r,['montant','valeur','value']),duration=str(first(r,['duree','duration','duree_mois','dureeMois']))||null,winner=first(r,['titulaire','winner','contractor','entreprise','titulaire_nom','attributaire','titulaire_denomination']),buyer=first(r,['nomacheteur','acheteur','organisme','acheteur_nom','acheteur_nom_officiel']);let p=0,e=0,reasons=[];if(!sec)return{score:0,evidence:0,confidence:'low',facts:{event_type:evt,sector:null,region:reg,amount_eur:amount,duration,winner:str(winner)||null,buyer:str(buyer)||null,reasons:['hors verticale TRIGORA']}};if(sec==='maintenance'&&!TECH.test(t))return{score:0,evidence:0,confidence:'low',facts:{event_type:evt,sector:null,region:reg,amount_eur:amount,duration,winner:str(winner)||null,buyer:str(buyer)||null,reasons:['maintenance non technique / hors wedge']}};p+=30;e++;reasons.push('activité technique ciblée');if(reg){p+=20;e++;reasons.push('zone Île-de-France')}if(evt==='attribution'){p+=25;e++;reasons.push('marché attribué')}else if(evt==='appel_offres'){p+=15;e++;reasons.push('opportunité active')}if(amount!=null){if(amount>=1e6)p+=15;else if(amount>=5e5)p+=12;else if(amount>=1e5)p+=8;else if(amount>=4e4)p+=4;if(amount>=1e5){e++;reasons.push('montant significatif')}}if(duration){p+=4;e++;reasons.push('durée renseignée')}if(winner){p+=4;e++;reasons.push('titulaire identifiable')}if(buyer){p+=2;e++;reasons.push('acheteur identifiable')}if(first(r,['idweb','id','uid','filename'])){p+=2;e++;reasons.push('source traçable')}const final=Math.min(p,100);return{score:final,evidence:e,confidence:final>=80&&e>=4?'high':final>=65&&e>=3?'medium':'low',facts:{event_type:evt,sector:sec,region:reg,amount_eur:amount,duration,winner:str(winner)||null,buyer:str(buyer)||null,reasons}}}
function inferIntent(f){const a=[],e=[];if(f.event_type==='attribution'){a.push('capacité opérationnelle / sous-traitance');e.push('contrat attribué')}if(f.amount_eur>=500000){a.push('BFR / financement');e.push('montant >= 500 k€')}if(f.duration&&/\d/.test(f.duration)){a.push('recrutement / renfort opérationnel');e.push('durée contractuelle')}if(['cvc','plomberie','electricite','maintenance'].includes(f.sector)){a.push('logiciel / gestion BTP');e.push('verticale technique')}if(f.region==='Île-de-France'){a.push('fournisseurs / prestataires locaux');e.push('zone IDF')}return{intents:[...new Set(a)].slice(0,5),confidence:Math.min(95,35+e.length*12+(f.event_type==='attribution'?12:0)+(f.amount_eur>=500000?10:0)),evidence:e,caveat:'Hypothèse commerciale : le signal indique un besoin potentiel, pas un besoin confirmé.'}}
function partnerMatches(f,intents){const m=[];if(intents.some(x=>x.includes('logiciel')))m.push({category:'SaaS BTP',reason:'gestion opérationnelle potentiellement pertinente',priority:3});if(intents.some(x=>x.includes('recrutement')))m.push({category:'RH / staffing',reason:'besoin potentiel de capacité',priority:3});if(intents.some(x=>x.includes('financement')))m.push({category:'financement B2B',reason:'contrat significatif pouvant créer un besoin de trésorerie',priority:2});if(intents.some(x=>x.includes('sous-traitance')))m.push({category:'réseau de sous-traitants',reason:'contrat attribué et capacité à absorber',priority:3});if(intents.some(x=>x.includes('fournisseurs')))m.push({category:'fournisseurs / équipements',reason:'activité locale ciblée',priority:2});return m.sort((a,b)=>b.priority-a.priority)}
function normalizeDecp(r){return{uid:first(r,['uid','id','marche_id','idweb']),nature:'Attribution DECP',objet:first(r,['objet','objet_du_marche','description']),code_departement:first(r,['code_departement','acheteur_code_departement','departement']),code_postal:first(r,['code_postal','acheteur_code_postal','cp']),ville:first(r,['ville','acheteur_ville','commune']),montant:first(r,['montant','montant_ht']),dureeMois:first(r,['dureeMois','duree_mois']),titulaire_nom:first(r,['titulaire_nom','titulaire_denomination']),titulaire_siret:first(r,['titulaire_siret']),acheteur_nom:first(r,['acheteur_nom','acheteur_nom_officiel']),dateNotification:first(r,['dateNotification','date_notification'])}}
function build(records,source='BOAMP'){const now=new Date().toISOString(),seen=new Set();return records.map((r,i)=>{const q=score(r);if(q.score<55||q.facts.region!=='Île-de-France')return null;const rawId=str(first(r,['idweb','id','uid','filename']))||String(i+1),key=[source,rawId,q.facts.winner||''].join('|').toLowerCase();if(seen.has(key))return null;seen.add(key);const intent=inferIntent(q.facts),matches=partnerMatches(q.facts,intent.intents);return{id:`trigora-${source.toLowerCase()}-${rawId.replace(/[^a-zA-Z0-9_-]/g,'-')}-${i}`,detected_at:now,score:q.score,confidence:q.confidence,company:q.facts.winner,buyer:q.facts.buyer,siret:str(first(r,['titulaire_siret','siret','contractor_siret','siren']))||null,title:str(first(r,['objet','object','title','intitule','description','objet_du_marche'])||'Marché public'),published_at:str(first(r,['dateparution','date_publication','date','dateNotification','date_notification'])||null),facts:q.facts,intent,match:{recommended:matches.slice(0,3)},monetization:{status:'not_connected',expected_revenue_eur:null},source:{system:source,dataset:source==='DECP'?'decp_consolide':'boamp_piamp_concentrateur',idweb:rawId,url:str(first(r,['url_avis','safe_url_avis','url']))||null,source_type:'open_public_data'}};}).filter(Boolean).sort((a,b)=>b.score-a.score)}
function getJson(url,timeout=2500){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'TRIGORA/1.6','Accept':'application/json'}},res=>{let body='';res.on('data',d=>body+=d);res.on('end',()=>{if(res.statusCode>=200&&res.statusCode<300){try{resolve(JSON.parse(body))}catch{reject(new Error('Invalid JSON from '+new URL(url).hostname))}}else reject(new Error(new URL(url).hostname+' HTTP '+res.statusCode))})});req.on('error',reject);req.setTimeout(timeout,()=>req.destroy(new Error(new URL(url).hostname+' timeout')))});}
async function fetchBoamp(limit){const qs=['plomberie','chauffage','climatisation','électricité','maintenance technique'];const per=Math.max(10,Math.ceil(Math.max(limit,80)/qs.length));const settled=await Promise.allSettled(qs.map(q=>getJson(BOAMP+'?'+new URLSearchParams({limit:String(per),where:`search(*, "${q.replace(/"/g,'')}" )`,order_by:'dateparution desc'})).then(x=>x.results||[])));const out=[],seen=new Set();for(const z of settled)if(z.status==='fulfilled')for(const r of z.value){const id=str(first(r,['idweb','id','filename']));if(!id||!seen.has(id)){if(id)seen.add(id);out.push(r)}}return out.sort((a,b)=>str(first(b,['dateparution'])).localeCompare(str(first(a,['dateparution'])))).slice(0,Math.max(limit,80))}
function fetchDecp(limit){const d=new Date(Date.now()-30*86400000).toISOString().slice(0,10);return getJson(DECP+'?'+new URLSearchParams({page_size:String(Math.min(Math.max(limit,100),200)),dateNotification__greater:d,donneesActuelles__exact:'true'})).then(x=>x.data||x.results||[])}
module.exports=async(req,res)=>{const limit=Math.min(Math.max(Number(req.query.limit||40),1),50),source=str(req.query.source||'both').toLowerCase();let boamp=[],decp=[];const tasks=[];if(source==='boamp'||source==='both')tasks.push(fetchBoamp(limit).then(x=>{boamp=x}));if(source==='decp'||source==='both')tasks.push(fetchDecp(limit).then(x=>{decp=x}));const settled=await Promise.allSettled(tasks),errors=settled.filter(x=>x.status==='rejected').map(x=>x.reason.message),signals=[...build(boamp,'BOAMP'),...build(decp.map(normalizeDecp),'DECP')].sort((a,b)=>b.score-a.score).slice(0,100);res.statusCode=200;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');res.end(JSON.stringify({success:true,generated_at:new Date().toISOString(),source,scope:'Île-de-France / technique BTP',source_records:{BOAMP:boamp.length,DECP:decp.length},signal_count:signals.length,upstream_errors:errors,signals}))};
module.exports._test={build,score,inferIntent,partnerMatches,normalizeDecp};